name: VolmitSoftware

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/VolmitSoftware.yml'
  schedule:
    - cron: '0 0 * * *'

jobs:
  Iris:
    uses: HSGamer/ConstructProjects/.github/workflows/gradle-build.yml@main
    with:
      repository: "VolmitSoftware/Iris"
      name: "Iris"
      java: "17"
  Adapt:
    uses: HSGamer/ConstructProjects/.github/workflows/gradle-build.yml@main
    with:
      repository: "VolmitSoftware/Adapt"
      name: "Adapt"
      java: "17"
  React:
    uses: HSGamer/ConstructProjects/.github/workflows/gradle-build.yml@main
    with:
      repository: "VolmitSoftware/React"
      name: "React"
      java: "17"
      tasks: "shadowJar"
      commands: "cd ./React"
      target: "React/build/libs/*.jar"
